rune_node:
   ros__parameters:
      # rune_target parameters
      rune_target:
         RADIUS: 150.
         ACTIVE_MIN_AREA: 60.
         ACTIVE_MAX_AREA: 20000.
         ACTIVE_MIN_SIDE_RATIO: 9.9000000953674316e-01
         ACTIVE_MAX_SIDE_RATIO: 3.
         ACTIVE_MIN_AREA_RATIO: 8.0000001192092896e-01
         ACTIVE_MAX_AREA_RATIO: 1.2000000476837158e+00
         ACTIVE_MAX_PERI_RATIO: 8.0000001192092896e-01
         ACTIVE_MAX_CONVEX_AREA_RATIO: 1.1000000238418579e+00
         ACTIVE_MAX_CONVEX_PERI_RATIO: 1.2000000476837158e+00
         ACTIVE_MIN_AREA_RATIO_SUB: 3.4999999403953552e-01
         ACTIVE_MAX_AREA_RATIO_SUB_TEN_RING: 3.0000001192092896e-01
         ACTIVE_DEFAULT_SIDE: 50.
         ACTIVE_3D: [0., 0., 0.]

         INACTIVE_MIN_AREA: 60.
         INACTIVE_MAX_AREA: 20000.
         INACTIVE_MIN_SIDE_RATIO: 9.9000000953674316e-01
         INACTIVE_MAX_SIDE_RATIO: 1.5499999523162842e+00
         INACTIVE_MIN_AREA_RATIO: 8.0000001192092896e-01
         INACTIVE_MAX_AREA_RATIO: 1.2000000476837158e+00
         INACTIVE_MIN_PERI_RATIO: 3.4999999403953552e-01
         INACTIVE_MAX_PERI_RATIO: 8.0000001192092896e-01
         INACTIVE_3D: [0., 0., 0.]

         GAP_MIN_AREA_RATIO: 2.5000000372529030e-02
         GAP_MAX_AREA_RATIO: 2.0000000298023224e-01
         GAP_MIN_SIDE_RATIO: 1.5499999523162842e+00
         GAP_MAX_SIDE_RATIO: 8.0000001192092896e-01
         GAP_CIRCLE_RADIUS_RATIO: 7.0370000600814819e-01
         GAP_MAX_DISTANCE_RATIO: 8.0000001192092896e-01
         GAP_MIN_DISTANCE_RATIO: 5.0000000000000000e-01
         GAP_3D:
            [
               -6.7175003099999998e+01,
               -6.7175003099999998e+01,
               0.,
               0.,
               -95.,
               0.,
               6.7175003099999998e+01,
               -6.7175003099999998e+01,
               0.,
               95.,
               0.,
               0.,
               6.7175003099999998e+01,
               6.7175003099999998e+01,
               0.,
               0.,
               95.,
               0.,
               -6.7175003099999998e+01,
               6.7175003099999998e+01,
               0.,
               -95.,
               0.,
               0.,
            ]
         ROTATION: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
         TRANSLATION: [0.0, 0.0, 0.0]

      # rune_target_draw parameters
      rune_target_draw:
         active_color: [0., 255., 0., 0.]
         active_thickness: 2
         active_point_radius: 3
         active_default_circle_radius: 150.

         inactive_color: [0., 255., 0., 0.]
         inactive_thickness: 2
         inactive_point_radius: 3
         inactive_default_circle_radius: 150.
         inactive_font_scale: 8.0000000000000004e-01
         inactive_font_thickness: 2
         inactive_font_color: [255., 255., 255., 0.]
